[2022-09-15 10:22:28,409] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2019-01-01T06:00:00+00:00 [queued]>
[2022-09-15 10:22:28,420] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2019-01-01T06:00:00+00:00 [queued]>
[2022-09-15 10:22:28,420] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-15 10:22:28,421] {taskinstance.py:1239} INFO - Starting attempt 4 of 4
[2022-09-15 10:22:28,421] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-15 10:22:28,471] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest> on 2019-01-01 06:00:00+00:00
[2022-09-15 10:22:28,475] {standard_task_runner.py:52} INFO - Started process 1557 to run task
[2022-09-15 10:22:28,480] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2019-01-01T06:00:00+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_dag.py', '--cfg-path', '/tmp/tmpy6owdnwm', '--error-file', '/tmp/tmp7q206q49']
[2022-09-15 10:22:28,481] {standard_task_runner.py:77} INFO - Job 181: Subtask ingest
[2022-09-15 10:22:28,555] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2019-01-01T06:00:00+00:00 [running]> on host 1bec96cb997e
[2022-09-15 10:22:28,749] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-09-15 10:22:28,790] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T06:00:00+00:00
[2022-09-15 10:23:39,790] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2022-09-15 10:23:39,834] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20190101T060000, start_date=20220915T102228, end_date=20220915T102339
[2022-09-15 10:23:40,566] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-17 03:08:48,709] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2019-01-01T06:00:00+00:00 [queued]>
[2022-09-17 03:08:48,729] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2019-01-01T06:00:00+00:00 [queued]>
[2022-09-17 03:08:48,730] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 03:08:48,730] {taskinstance.py:1239} INFO - Starting attempt 4 of 4
[2022-09-17 03:08:48,730] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 03:08:48,770] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest> on 2019-01-01 06:00:00+00:00
[2022-09-17 03:08:48,775] {standard_task_runner.py:52} INFO - Started process 5751 to run task
[2022-09-17 03:08:48,778] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2019-01-01T06:00:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_dag.py', '--cfg-path', '/tmp/tmpiaatdtco', '--error-file', '/tmp/tmptd8d2rds']
[2022-09-17 03:08:48,779] {standard_task_runner.py:77} INFO - Job 254: Subtask ingest
[2022-09-17 03:08:48,873] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2019-01-01T06:00:00+00:00 [running]> on host 5d94276fbe2b
[2022-09-17 03:08:48,956] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-09-17 03:08:49,037] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T06:00:00+00:00
[2022-09-17 03:08:49,039] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-09-17 03:08:49,041] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-09-17 03:08:49,042] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-09-17 03:08:49,043] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-09-17 03:08:49,044] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-09-17 03:08:49,045] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-09-17 03:08:49,047] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-09-17 03:08:49,050] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-09-17 03:08:49,052] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-09-17 03:08:49,054] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-09-17 03:08:49,055] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-09-17 03:08:49,056] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_dag.py", line 25, in ingest_call
    engine = engine_creation.xcom_pull(task_ids='eng')
TypeError: xcom_pull() missing 1 required positional argument: 'context'
[2022-09-17 03:08:49,079] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20190101T060000, start_date=20220917T030848, end_date=20220917T030849
[2022-09-17 03:08:49,126] {standard_task_runner.py:92} ERROR - Failed to execute job 254 for task ingest
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_dag.py", line 25, in ingest_call
    engine = engine_creation.xcom_pull(task_ids='eng')
TypeError: xcom_pull() missing 1 required positional argument: 'context'
[2022-09-17 03:08:49,153] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-17 03:08:49,303] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
