[2022-09-17 03:25:24,881] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.eng scheduled__2019-01-01T06:00:00+00:00 [queued]>
[2022-09-17 03:25:24,892] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.eng scheduled__2019-01-01T06:00:00+00:00 [queued]>
[2022-09-17 03:25:24,893] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 03:25:24,893] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-09-17 03:25:24,894] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 03:25:25,008] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): eng> on 2019-01-01 06:00:00+00:00
[2022-09-17 03:25:25,012] {standard_task_runner.py:52} INFO - Started process 7284 to run task
[2022-09-17 03:25:25,016] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'eng', 'scheduled__2019-01-01T06:00:00+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_dag.py', '--cfg-path', '/tmp/tmp00p_nfbm', '--error-file', '/tmp/tmp6wbhtrvs']
[2022-09-17 03:25:25,017] {standard_task_runner.py:77} INFO - Job 265: Subtask eng
[2022-09-17 03:25:25,247] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.eng scheduled__2019-01-01T06:00:00+00:00 [running]> on host 5d94276fbe2b
[2022-09-17 03:25:25,357] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=eng
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T06:00:00+00:00
[2022-09-17 03:25:25,358] {logging_mixin.py:109} INFO - root   root   docker_sql_0_pgdatabase_1   5432   ny_taxi
[2022-09-17 03:25:25,359] {python.py:175} INFO - Done. Returned value was: Engine(postgresql://root:***@docker_sql_0_pgdatabase_1:5432/ny_taxi)
[2022-09-17 03:25:25,360] {xcom.py:334} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-09-17 03:25:25,361] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2141, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 100, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 331, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Engine is not JSON serializable
[2022-09-17 03:25:25,411] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=eng, execution_date=20190101T060000, start_date=20220917T032524, end_date=20220917T032525
[2022-09-17 03:25:25,497] {standard_task_runner.py:92} ERROR - Failed to execute job 265 for task eng
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2141, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 100, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 331, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Engine is not JSON serializable
[2022-09-17 03:25:25,512] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-17 03:25:25,598] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
